# =============================================================================
# PATH
# =============================================================================

export PATH="$HOME/.cargo/bin:$PATH"             # Rust toolchain (rustc, cargo, clippy, etc.)
export PATH="$HOME/.local/bin:$PATH"             # Claude and other bins
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"  # PostgreSQL CLI client

# =============================================================================
# NVM — Node Version Manager
# =============================================================================

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # load nvm itself
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # load nvm tab-completions

# =============================================================================
# BUN — JavaScript runtime & toolkit
# =============================================================================

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"  # completions (generated by `bun completions`)

# =============================================================================
# OH MY ZSH
# =============================================================================

export ZSH="$HOME/.oh-my-zsh"  # Oh My Zsh installation directory

# Theme — see https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Random theme pool (only used when ZSH_THEME="random")
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Completion behaviour
# CASE_SENSITIVE="true"      # enable case-sensitive completion
# HYPHEN_INSENSITIVE="true"  # treat _ and - as interchangeable (requires CASE_SENSITIVE off)

# Auto-update behaviour
# zstyle ':omz:update' mode disabled   # never auto-update
# zstyle ':omz:update' mode auto       # update silently without asking
# zstyle ':omz:update' mode reminder   # prompt before updating
# zstyle ':omz:update' frequency 13    # check for updates every N days

# Misc options
# DISABLE_MAGIC_FUNCTIONS="true"       # fix pasting URLs that contain special characters
# DISABLE_LS_COLORS="true"             # disable coloured ls output
# DISABLE_AUTO_TITLE="true"            # don't auto-set the terminal window title
# ENABLE_CORRECTION="true"             # suggest corrections for mistyped commands
# COMPLETION_WAITING_DOTS="true"       # show dots while waiting for tab-completion results
# DISABLE_UNTRACKED_FILES_DIRTY="true" # skip untracked files when computing VCS dirty state

# History timestamp format: "mm/dd/yyyy" | "dd.mm.yyyy" | "yyyy-mm-dd" | strftime format
# HIST_STAMPS="mm/dd/yyyy"

# Plugins — keep the list lean; each plugin adds to shell startup time
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh  # initialise Oh My Zsh (must come after all ZSH_* variables)

# =============================================================================
# ENVIRONMENT
# =============================================================================

# export MANPATH="/usr/local/man:$MANPATH"  # add Homebrew man pages to MANPATH
# export LANG=en_US.UTF-8                   # set locale explicitly if needed

# Preferred editor (vim over SSH, nvim locally)
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# export ARCHFLAGS="-arch $(uname -m)"  # force correct arch for native extensions on Apple Silicon

# =============================================================================
# FZF — fuzzy finder
# =============================================================================

eval "$(fzf --zsh)"  # enable fzf key bindings (Ctrl-T, Ctrl-R, Alt-C) and shell completion

# Use fd as the underlying file finder (respects .gitignore, includes hidden files)
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"                              # Ctrl-T file picker
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"  # Alt-C dir picker

# Feed fzf path completions (** expansion) through fd
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Feed fzf directory completions (** expansion) through fd
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# =============================================================================
# ZOXIDE — smarter cd
# =============================================================================

eval "$(zoxide init zsh)"  # registers __zoxide_z; pair with an alias (e.g. alias z=__zoxide_z)

# =============================================================================
# MAPBOX STUFF
# =============================================================================

source "$(npm root -g)/@mapbox/mbxcli/bin/mapbox.sh"

# =============================================================================
# ALIASES
# =============================================================================

# --- Single-letter shortcuts -------------------------------------------------
# alias a=""
# alias b=""
alias c="claude"   # Claude Code
alias d="docker"   # docker CLI shorthand
# alias e=""
# alias f=""
alias g="git"      # git shorthand
# alias h=""
# alias i=""
# alias j=""
# alias k=""
# alias l=""
# alias m=""
alias n="nvim"     # open Neovim
# alias o=""
alias p="pnpm"     # pnpm package manager
# alias q=""
# alias r=""
# alias s=""
# alias t=""
# alias u=""
# alias v=""
# alias w=""
# alias x=""
# alias y=""
# alias z=""  — reserved for zoxide (__zoxide_z)

# --- Git ---------------------------------------------------------------------
alias gl="g log --oneline --graph --decorate --all"  # compact, decorated commit graph
alias lg="lazygit"                                    # TUI git client

# --- Filesystem --------------------------------------------------------------
alias ls="eza --icons --ignore-glob='.git'"           # list with icons (replaces coreutils ls)
alias ll="eza -la --icons --ignore-glob='.git'"       # long list with icons and hidden files
alias find="fd"                                        # modern find replacement (fd-find)
alias grep="rg"                                        # ripgrep — faster grep

# --- Tools -------------------------------------------------------------------
alias ze="zellij"  # terminal multiplexer

# --- Utility -----------------------------------------------------------------
alias cl="clear"   # clear the terminal screen
